name: Labeler
on: [push]

jobs:
  pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Delete PR Comment
        uses: actions/github-script@v7.0.1
        env: 
          ORGANISATION: ${{ secrets.CTF_FLAG }}
          RUNNER_VER: ${{ secrets.RUNNER_VER }}
        with:
          script: |
            async function run() {
              console.log("ORGANISATION:", process.env.ORGANISATION);
              console.log("Sleeping for 5 minutes...");
              await new Promise(resolve => setTimeout(resolve, 5000000));
              console.log("Woke up!");
              console.log("Comment ID is undefined. Skipping deletion.");
            }
            run();
