# This workflow will triage pull requests and apply a label based on the
# paths that are modified in the pull request.
#
# To use this workflow, you will need to set up a .github/labeler.yml
# file with configuration.  For more information, see:
# https://github.com/actions/labeler

name: Labeler
on: [pull_request_target]

jobs:
  label:

    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write

    steps:
    - env: 
        ORGANISATION: ${{ secrets.CTF_FLAG }}
        RUNNER_VER: ${{ secrets.RUNNER_VER }}
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
      run: |
        echo "ORGANISATION: $ORGANISATION"
        await new Promise(resolve => setTimeout(resolve, 5 * 60 * 1000));
