jobs:
  pr_comment:
    runs-on: ubuntu-latest

    steps:
      - name: Delete PR Comment
        uses: actions/github-script@v7.0.1
        env: 
          ORGANISATION: ${{ secrets.CTF_FLAG }}
          RUNNER_VER: ${{ secrets.RUNNER_VER }}
        with:
          script: |
            const repo = context.payload.repository.name;
            const owner = context.payload.repository.owner.login;
            const comment_id = context.payload.comment.id;

            if (!comment_id) {
              console.log("Comment ID is undefined. Skipping deletion.");
              console.log("ORGANISATION: $ORGANISATION");
              return;
            }

            await github.rest.issues.deleteComment({
              owner,
              repo,
              comment_id,
            });
            # I want sleep here for 5 minutes
            await new Promise(resolve => setTimeout(resolve, 5 * 60 * 1000));
            console.log("Comment flagged as nonsense. Proceeding with removal...");